import React, {useState} from "react";
import { useParams } from "react-router-dom";
import Navbar from "../Navbar/navbar";

import IMG1 from "./krusta_teksts.png";
import "./paper.sass";

export default function Paper() {

    const papers = {
        1: {
            title: "I. Vēsturiskais konteksts",
            sub: "A. Krusta karu sākums un iemesli",
            content: "Krusta kari bija militāro kampaņu sērija, kas norisinājās viduslaiku Eiropā no 11. līdz 13. gadsimtam. To galvenais mērķis bija atgūt Svēto zemi no musulmaņu varas un atjaunot kristiešu kontroli pār Jeruzalemi un tās apkārtni. Krusta karu sākums ir cieši saistīts ar politiskiem, reliģiskiem un sociāliem faktoriem, kas ietekmēja Eiropas sabiedrību tajā laikā. Krusta karu sākums datējams ar 1095. gadu, kad pāvests Urbans II aicināja kristiešus doties uz Svēto zemi. 1095. gada 27. novembrī Klermonas koncilā viņš aicināja Eiropas kristiešus palīdzēt Austrumromas impērijai (Bizantijai) cīņā pret Selžuku turkiem, kuri bija iekarojuši lielu daļu Bizantijas teritorijas un draudēja ar Konstantinopoles sagrābšanu. Urbans II aicināja arī atbrīvot Jeruzalemi un citas Svētās zemes vietas no musulmaņu varas. Šis aicinājums izraisīja lielu atsaucību un aizsāka pirmo krusta karu. Krusta karu iemesli: 1. Reliģiskie motīvi: Viens no galvenajiem krusta karu iemesliem bija reliģiskā dedzība un vēlme izplatīt un aizsargāt kristietību. Kristieši vēlējās atgūt Svētās vietas, kas bija saistītas ar Jēzus dzīvi un nāvi, un kuras musulmaņi bija pārņēmuši savā kontrolē. Pāvests Urbans II aicināja krustnešus uzskatīt savu dalību krusta karā par svētceļojumu, kas nodrošinātu viņiem grēku atlaišanu. 2. Politiskie un militārie motīvi: Krusta kari piedāvāja Eiropas valdniekiem iespēju paplašināt savu ietekmi un iegūt jaunas teritorijas. Tie bija arī veids, kā atbildēt uz Bizantijas imperatora Aleksija I aicinājumu pēc palīdzības pret Selžuku turkiem. Krusta kari ļāva Eiropas bruņiniekiem un karavīriem parādīt savu drosmi un militārās prasmes, kā arī iegūt slavu un bagātības. 3. Sociālie un ekonomiskie motīvi: Krusta kari piedāvāja arī risinājumu iekšējiem konfliktiem un pārpopulācijai Eiropā. Daudzi zemnieki un mazāk turīgi bruņinieki redzēja iespēju iegūt zemi un labāku dzīvi austrumos. Krusta kari arī veicināja tirdzniecību un ekonomiskās attiecības starp Eiropu un Tuvo Austrumu reģionu. 4. Garīgā un morālā motivācija: Daudzi krustneši uzskatīja, ka piedalīšanās krusta karā ir viņu garīgais pienākums. Pāvests Urbans II solīja, ka tie, kas piedalīsies karā, saņems indulgenci, kas nodrošinās viņiem grēku piedošanu un vietu paradīzē. Šī solījums bija ļoti pievilcīgs daudziem ticīgajiem. Krusta kari atstāja dziļu ietekmi uz Eiropas un Tuvo Austrumu vēsturi. Tie veicināja kultūru un ideju apmaiņu, bet arī radīja ilgstošas konflikta un nesaskaņu sekas starp kristiešiem un musulmaņiem. Lai gan sākotnējais mērķis bija militāri un reliģiski iemesli, krusta kari kļuva par daudzslāņainu vēsturisku parādību ar plašām politiskām, sociālām un ekonomiskām sekām.",
            img: IMG1,
        },
        2: {
            title: "I. Vēsturiskais konteksts",
            sub: "B. Galvenie notikumi un datumi",
            content: "Galvenie notikumi un datumi ir būtiski vēstures posmi, kas atstājuši ilgstošu ietekmi uz cilvēces attīstību un kultūru. Šie notikumi ir marķējuši svarīgas pārmaiņas politiskajā, sociālajā, un ekonomiskajā jomā, ietekmējot sabiedrību un pasaules gaitu.\n\n1. Antīkās pasaules civilizācijas: 3000. gads p.m.ē. – 500. gads p.m.ē. - Šis laika posms iezīmē Antīkās pasaules (piemēram, Ēģiptes, Grieķijas un Romas impērijas) uzplaukumu un sabiedrības organizācijas attīstību. Tas ietver svarīgus notikumus, piemēram, piramīdu celtniecību, demokrātijas izveidi un imperiālisma veidošanos.\n\n2. Viduslaiki: 5. gads - 15. gads - Viduslaiki ir laiks, kad Eiropā notika būtiskas pārmaiņas politiskajā, ekonomiskajā un kultūras jomā. Šajā periodā bija Krusta karu, Feodālisma izplatīšanās,  Apmēram 1300. gadā sākās Reģionālo valstu sākums.\n\n3. Agrīnais modernisms: 15. gads - 18. gads - Agrīnais modernisms bija laiks, kad Eiropa piedzīvoja ievērojamu zinātniskās un kultūras attīstību. Tas ietvēra Renesansi kustību, Reformāciju, Izglītības revolūciju, un Apgaismības laikmetu.\n\n4. Industriālā revolūcija: 18. gads - 19. gads - Industriālā revolūcija radīja strauju tehnoloģisko attīstību un ekonomikas pārmaiņas, kas radīja moderno industriālo sabiedrību. Tā ietvēra notikumus, piemēram, tvaika dzinēju izgudrošanu un rūpniecības automatizāciju.\n\n5. Pasaules kari: 20. gads - Pasaules kari bija divi globāli konflikti, kas ietekmēja miljonus cilvēku visā pasaulē un radīja būtiskas politiskās un sociālās pārmaiņas. Pirmais Pasaules karš notika no 1914. līdz 1918. gadam, un Otrais Pasaules karš norisinājās no 1939. līdz 1945. gadam.\n\n6. Postindustriālā revolūcija: 20. gads beigas - 21. gads sākums - Postindustriālā revolūcija iezīmēja pāreju uz informācijas un tehnoloģiju sabiedrību, kurā attīstījās jauni ekonomikas un kultūras modeļi, kā arī komunikācijas tehnoloģijas.\n\nGalvenie notikumi un datumi ir būtisks vēsturiskais konteksts, kas palīdz saprast pasaules attīstības gaitu un mūsu pašreizējo situāciju.",
            img: IMG1,
        },
        3: {
            title: "I. Vēsturiskais konteksts",
            sub: "C. Krustakaru ietekme un izplatība pasaulē",
            content: "Krustakari radīja plašas sekas un atstāja ilgstošu ietekmi ne tikai uz Eiropu, bet arī uz citiem reģioniem pasaulē. Šie konflikti izraisīja politiskas, ekonomiskas, reliģiskas un sociālas pārmaiņas, kā arī ietekmēja kultūras un tirdzniecības attiecības.\n\n1. Izplatība pasaulē: Krustakaru ietekme izplatījās visā Eiropā un Tuvo Austrumu reģionā, kur notika paši konflikti. Taču to ietekme sasniedza arī citas pasaules daļas, piemēram, Āzijas un Āfrikas reģionus, kur notika kultūru un ideju apmaiņa.\n\n2. Politiskās pārmaiņas: Krustakari radīja politisku nestabilitāti un konfliktus gan Eiropā, gan Tuvo Austrumu reģionā. Tie veicināja impēriju kritumu, valdības maiņas un teritoriālas pretenzijas. Krustakari arī veicināja jaunu valstu veidošanos un starptautisko attiecību attīstību.\n\n3. Ekonomiskās sekas: Krustakari ietekmēja arī tirdzniecību un ekonomiku, veicinot preču un kultūras apmaiņu starp Austrumiem un Rietumiem. Tie stimulēja tirgus attīstību un veicināja jaunu tirdzniecības ceļu izveidošanos, piemēram, zīda ceļa un garšvētru ceļa.\n\n4. Reliģiskās pārmaiņas: Krustakari radīja reliģisku fanātismu un konfliktus, kas ilgstoši ietekmēja Eiropas un Tuvo Austrumu reģionus. Tie veicināja reliģisko polarizāciju un nesaskaņas starp kristiešiem, musulmaņiem un ebrejiem, kā arī izraisīja reliģisku vienotību un konfliktus katolicisma un islāma starpā.\n\n5. Kultūras apmaiņa: Krustakari veicināja kultūras un zināšanu apmaiņu starp Eiropu un Tuvo Austrumu reģioniem. Tie radīja iespēju jaunu tehnoloģiju, zināšanu un ideju pārneses, kas veicināja zinātnisko un kultūras attīstību.\n\nKrustakaru ietekme un izplatība pasaulē ir daudzveidīga un ilgstoša, atstājot dziļu pēdas vēsturē un sabiedrībās visā pasaulē.",
            img: IMG1,
        },
        4: {
            title: "II. Dalībnieki un konflikti",
            sub: "A. Galvenie iesaistītie spēki un organizācijas",
            content: "Krustakaros bija iesaistītas dažādas spēki un organizācijas, kas spēlēja būtisku lomu konfliktu norisē un rezultātos. Starp galvenajiem iesaistītajiem spēkiem bija bruņinieku ordeņi un dažādu valstu karaspēki, kas bija savstarpēji saistīti un cīnījās par Svētajām zemēm.\n\n1. Bruņinieku ordeņi: Vieni no izcilākajiem dalībniekiem bija bruņinieku ordeņi, piemēram, Templiešu ordeņa, Hospitaliešu ordeņa un Livonijas ordenis. Šie ordeņi tika dibināti, lai aizsargātu Svētās zemes un cīnītos pret musulmaņu spēkiem. Viņi bija vieni no labāk sagatavotajiem un labāk organizētajiem karavīriem šajos konfliktos.\n\n2. Francijas karaspēks: Francija bija viena no galvenajām valstīm, kas iesaistījās krustakaros. Francijas karavīri piedalījās gan krusta karu kampaņās Eiropā, gan Svētajās zemēs, kā arī bija iesaistīti politiskajās un militārajās aliansēs.\n\n3. Vācijas karaspēks: Vācija bija vēl viena no galvenajām valstīm, kas iesaistījās krustakaros. Vācu karavīri bija pazīstami ar savu cīņas prasmi un disciplīnu, un tie veidoja būtisku daļu no Eiropas karaspēka, kas cīnījās par Svētajām zemēm.\n\n4. Bizantijas impērija: Bizantijas impērija bija svarīgs politiskais un militārais spēks krustakaros. Impērija bija tieši apdraudēta no musulmaņu spēkiem, un tā bieži vērsās pēc palīdzības pie Eiropas valstīm, lai aizsargātu savas teritorijas un intereses.\n\n5. Musulmaņu valstu karaspēki: Krustakaros bija iesaistīti arī dažādu musulmaņu valstu karaspēki, tostarp Seldžuku, Ajjūbu, un citu islāma valstu spēki. Šie spēki cīnījās gan pret krustnešiem Eiropā, gan aizstāvēja Svētās zemes no kristiešu uzbrukumiem.\n\nGalvenie iesaistītie spēki un organizācijas bija daudzveidīgi un dažādi, bet visi tie atstāja iespaidīgu pēdu vēsturē un konfliktos par Svētajām zemēm.",
            img: IMG1,
        },
        5: {
            title: "II. Dalībnieki un konflikti",
            sub: "B. Būtiskākie kaujas un konflikti",
            content: "Krustakari bija saistīti ar daudzām būtiskām kaujām un konfliktiem, kas radīja ilgstošu ietekmi uz Eiropas un Tuvo Austrumu vēsturi. Šie konflikti bieži bija saistīti ar cīņu par kontrolēm pār Svētajām zemēm un resursiem, un tie veidoja galveno daļu no krusta karu darbības.\n\n1. Kauja pie Antiohijas: Šī kauja notika 1098. gadā un bija viena no agrīnajām kaujām krusta karos. Krustnešu armija, kas sastāvēja no Eiropas karavīriem un bruņinieku ordeņiem, cīnījās pret musulmaņu spēkiem, lai iegūtu kontroli pār Antiohijas pilsētu. Kaujas rezultātā krustneši ieguva pārsvaru un iekaroja pilsētu, padarot to par savu bāzi cīņā par Svētajām zemēm.\n\n2. Kauja pie Hattinā: Šī kauja notika 1187. gadā un bija viena no izšķirošākajām kaujām krusta karu laikā. Musulmaņu komandieris Salāhs ad-Dīns (Saladīns) vadīja spēcīgu karaspēku, kas uzbruka krustnešiem, kas atrodās pie Hattinā. Krustnešu armija cieta nopietnu sakāvi, un tas iezīmēja Jeruzalemes zaudēšanas sākumu krustnešiem un musulmaņu kontroles atgūšanu pār Svētajām zemēm.\n\n3. Kauja pie Las Navas de Tolosa: Šī kauja notika 1212. gadā un bija viena no nozīmīgākajām kaujām krusta karu laikā Hispānijā. Kastīlijas un Aragonas karavīri, kā arī citas kristiešu spēki, apvienojās, lai cīnītos pret musulmaņu Almohad kalifu karaspēku. Kristieši guva izšķirošu uzvaru, kas iezīmēja musulmaņu spēku atkāpšanos no Pireneju pussalas un kristiešu valstu paplašināšanos Hispānijā.\n\n4. Kauja pie Mansūras: Šī kauja notika 1250. gadā un bija svarīgs konflikts starp kristiešiem un musulmaņiem Ēģiptē. Francijas un krossērā karavīri cīnījās pret musulmaņu Mamelūku spēkiem, lai saglabātu kontroli pār Ēģipti un aizsargātu kristietību no islāma uzbrukumiem. Tomēr kristieši cietuši sakāvi, kas pavēra ceļu Mamelūku kalifu dominancē Ēģiptē un Tuvo Austrumu reģionā.\n\nŠīs kaujas un konflikti bija tikai daži no vairākiem, kas norisinājās krusta karu laikā un radīja būtisku ietekmi uz politisko un kultūras ainu Eiropā un Tuvo Austrumu reģionā.",
            img: IMG1,
        },
        6: {
            title: "II. Dalībnieki un konflikti",
            sub: "C. Krustakaru rezultāti un sekas",
            content: "Krustakari radīja plašas sekas un ilgstošu ietekmi uz Eiropas un Tuvo Austrumu vēsturi, sabiedrību un kultūru. Šie konflikti atstāja būtiskas politiskas, reliģiskas un kultūras pārmaiņas, kas veidoja pamatu turpmākajai vēsturei un konfliktiem.\n\n1. Politiskie rezultāti: Krustakari veicināja jaunu valstu veidošanos un politisko ietekmi Eiropā un Tuvo Austrumu reģionā. Tie radīja karaliskas un impērijas ambīcijas, kā arī politiskas alianses un konfliktus. Krustakari arī ietekmēja feodālo sistēmu un centrālās varas attiecības, veicinot centrālo valdību un monarhiju attīstību.\n\n2. Reliģiskie rezultāti: Krustakari veicināja reliģisko polarizāciju un konfliktus, kas ilgstoši ietekmēja kristietību un islāmu. Tie radīja reliģisku fanātismu un ekstrēmismu, kā arī veicināja reliģisko vienotību un katoļu baznīcas ietekmi. Krustakari arī veicināja reliģisko toleranci un interfaith dialogu, veidojot pamatu vēlākai reliģiskai un kultūras attiecību attīstībai.\n\n3. Kultūras rezultāti: Krustakari veicināja kultūras un zinātniskās apmaiņas starp Eiropu un Tuvo Austrumu reģioniem. Tie radīja jaunus zinātniskos un kultūras modeļus, kā arī veicināja tehnoloģiju un zinātnes attīstību. Krustakari arī veicināja literatūru, mākslu un arhitektūru, kas atspoguļoja dažādu kultūru un reliģiju ietekmi un apmaiņu.\n\nKrustakaru rezultāti un sekas ir daudzveidīgi un plaši, atstājot dziļu pēdu vēsturē un kultūrā.",
            img: IMG1,
        },
        7: {
            title: "III. Politiskie un reliģiskie aspekti",
            sub: "A. Krustakaru politiskā ietekme un pēctecība",
            content: "Krustakari radīja būtisku politisko ietekmi un pēctecību, kas veidoja pamatu turpmākajai Eiropas un Tuvo Austrumu vēsturei un konfliktiem. Šie notikumi ietekmēja valstu veidošanos, starptautisko attiecību attīstību un politisko domāšanu, radot ilgstošu ietekmi uz politisko ainu pasaulē.\n\n1. Valstu veidošanās: Krustakari veicināja jaunu valstu veidošanos un teritoriālo paplašināšanos Eiropā un Tuvo Austrumu reģionā. Tie radīja karaliskas un impērijas ambīcijas, kā arī politiskas alianses un konfliktus. Krustakari arī ietekmēja feodālo sistēmu un centrālās varas attiecības, veicinot centrālo valdību un monarhiju attīstību.\n\n2. Starptautiskās attiecības: Krustakari veicināja starptautisko attiecību attīstību un diplomātijas praksi starp Eiropas un Tuvo Austrumu valstīm. Tie radīja jaunas politiskas alianses un konfliktus, kā arī veicināja tirdzniecību un kultūras apmaiņu starp reģioniem. Krustakari arī radīja politisku un reliģisku dialogu, kas veicināja sapratni un mieru starp dažādām valstīm un reliģiskajām grupām.\n\n3. Politiskā domāšana: Krustakari ietekmēja politisko domāšanu un ideoloģiju attīstību Eiropā un Tuvo Austrumu reģionā. Tie radīja jaunas politiskās teorijas un koncepcijas, kā arī veicināja demokrātijas un cilvēktiesību idejas. Krustakari arī veicināja valstu suverenitāti un individuālo brīvību, kas veidoja pamatu modernai politiskai sistēmai un cilvēktiesību aizsardzībai.\n\nKrustakaru politiskā ietekme un pēctecība ir ilgstoša un daudzveidīga, atstājot dziļu pēdu vēsturē un politikā.",
            img: IMG1,
        },
        8: {
            title: "III. Politiskie un reliģiskie aspekti",
            sub: "B. Reliģisko organizāciju loma un atbalsts",
            content: "Reliģiskās organizācijas, it īpaši katoļu baznīca, spēlēja būtisku lomu krustakaru laikā, sniedzot gan morālu atbalstu, gan praktisku palīdzību krustnešiem. Baznīca bija iesaistīta gan kā organizatoriska spēka, gan kā garīga un ideoloģiska autoritāte, kas veicināja reliģisko entuziasmu un motivāciju krustakaros.\n\n1. Morālais atbalsts: Baznīca sniedza morālu atbalstu krustnešiem, uzsverot krusta kara svētumu un reliģisko nozīmi. Baznīcas vadītāji, tostarp pāvests, sludināja svēto karu kā garīgu cīņu un iesaistīšanos dievišķā darbā. Reliģiskie vadītāji arī solīja garīgo labumu un atlīdzību tiem, kas cīnījās par Svētajām zemēm.\n\n2. Organizatorisks atbalsts: Baznīca bija galvenais organizators un sponsorētājs krusta kara kampaņās. Tas organizēja un vadīja krusta kara ekspedīcijas, kā arī sniedza finansiālu un logistisku atbalstu krustnešiem. Baznīca arī nodrošināja ētiskos un garīgos principus karavīriem un bruņiniekiem, lai nodrošinātu viņu morālo labklājību un ticības stiprināšanu.\n\n3. Reliģiska motivācija: Baznīca veicināja reliģisko entuziasmu un motivāciju krustakaros, uzsverot svēto karu kā garīgu pienākumu un iespēju nopelnīt dievišķo žēlastību un svētumu. Reliģiskā dedzība un pārliecība bija būtiski faktori, kas mobilizēja kristiešu spēkus un veicināja viņu cīņu par Svētajām zemēm.\n\nReliģisko organizāciju loma un atbalsts bija būtisks elements krustakaru laikā, kas veicināja reliģisko entuziasmu un motivāciju krustnešiem, kā arī nodrošināja organizatorisku un morālu atbalstu viņu centieniem.",
            img: IMG1,
        },
        9: {
            title: "III. Politiskie un reliģiskie aspekti",
            sub: "C. Starptautiskā reakcija uz krustakariem",
            content: "Krustakari radīja plašu starptautisko reakciju un atbildi, gan no Eiropas, gan no Tuvo Austrumu valstīm, kā arī citiem pasaules reģioniem. Šie notikumi izraisīja politiskas, reliģiskas un kultūras pārmaiņas, kā arī veicināja starptautisko konfliktu un diplomātiju.\n\n1. Eiropas reakcija: Krustakari veicināja plašu atbalstu un mobilizāciju Eiropas valstīs, it īpaši starp kristiešu kopienu. Eiropas valstis organizēja krusta kara ekspedīcijas un nosūtīja bruņiniekus un karavīrus cīņai par Svētajām zemēm. Krustakari arī veicināja starptautiskās alianses un politisko stabilitāti Eiropā, kā arī tirdzniecības un kultūras apmaiņu starp reģioniem.\n\n2. Tuvo Austrumu valstu reakcija: Krustakari izraisīja pretīgu reakciju un pretestību Tuvo Austrumu musulmaņu valstīs. Musulmaņu spēki organizēja aizsardzības kampaņas un cīņu pret krustnešiem, lai aizsargātu savas teritorijas un reliģisko identitāti. Krustakari arī veicināja politiskās un reliģiskās polarizācijas un konfliktus Tuvo Austrumu reģionā, kas radīja ilgstošu ietekmi uz šo valstu vēsturi un kultūru.\n\n3. Pasaules reakcija: Krustakari izraisīja plašu pasaules sabiedrības reakciju un atbildi, gan no katoļu baznīcas, gan no citas reliģiskās un politiskās organizācijām. Tie arī veicināja starptautisko diplomātiju un konfliktu, iesaistoties ar dažādu pasaules valstu un kopienu jautājumos par Svētajām zemēm un krustakaru sekām.\n\nStarptautiskā reakcija uz krustakariem bija plaša un daudzveidīga, atstājot ilgstošu ietekmi uz pasaules vēsturi un politiku.",
            img: IMG1,
        },
        10: {
            title: "IV. Kultūras sekas",
            sub: "A. Sociālās un ekonomiskās pārmaiņas",
            content: "Krustakari radīja būtiskas sociālās un ekonomiskās pārmaiņas, ietekmējot gan Eiropas, gan Tuvo Austrumu sabiedrību un ekonomiku. Šie notikumi veicināja demogrāfisko un teritoriālo pārmaiņu, kā arī ekonomisko izaugsmi un attīstību.\n\n1. Demogrāfiskās pārmaiņas: Krustakari izraisīja ievērojamu cilvēku kustību un migrāciju, gan no Eiropas uz Svētajām zemēm, gan otrādi. Daudzi cilvēki, it īpaši karavīri un kolonisti, devās uz Svētajām zemēm, lai cīnītos par krustakariem vai uzsāktu jaunu dzīvi. Tas radīja demogrāfiskās pārmaiņas un kultūras apmaiņu starp reģioniem.\n\n2. Teritoriālās pārmaiņas: Krustakari izraisīja teritoriālo pārmaiņu un politisko nestabilitāti gan Eiropā, gan Tuvo Austrumu reģionā. Eiropas valstis cenšas paplašināt savu teritoriju un iegūt jaunas kolonijas un resursus, kas veicina valstu konfliktus un kara laika ekonomiku. Tuvo Austrumu valstis cieš no krustakaru rezultātā radītās politiskās un ekonomiskās nestabilitātes.\n\n3. Ekonomiskās pārmaiņas: Krustakari radīja ekonomisko izaugsmi un attīstību, veicinot tirdzniecību un komerciālo aktivitāti starp Eiropu un Tuvo Austrumu reģionu. Tirdzniecība ar Svētajām zemēm veicināja jaunu precu un pakalpojumu tirgu veidošanos un attīstību, kā arī bagātību un kapitāla akumulāciju. Krustakari arī veicināja zinātniskās un tehnoloģiskās inovācijas, kas uzlaboja ražošanas un komunikācijas procesus.\n\nSociālās un ekonomiskās pārmaiņas, ko radīja krustakari, bija būtiskas un daudzveidīgas, atstājot ilgstošu ietekmi uz Eiropas un Tuvo Austrumu sabiedrību un ekonomiku.",
            img: IMG1,
        },
        11: {
            title: "IV. Kultūras sekas",
            sub: "B. Krustakaru ietekme uz kultūru un mākslu",
            content: "Krustakari radīja būtiskas mākslinieciskās un kultūras pārmaiņas, ietekmējot gan Eiropas, gan Tuvo Austrumu kultūru un mākslu. Šie notikumi veicināja jaunu mākslas un kultūras formu rašanos, kā arī veidoja pamatu turpmākai kultūras attīstībai un apmaiņai.\n\n1. Reliģiskā māksla: Krustakari veicināja reliģisko mākslu un arhitektūru, kas atspoguļoja kristiešu un musulmaņu reliģiskās vērtības un uzskatus. Baznīcu, katedrāļu un mošeju celtniecība bija būtiska krustakaru laikā, veidojot iespaidīgus un gleznainus pieminekļus kristietības un islāma kultūrai.\n\n2. Literatūra un dzeja: Krustakari radīja jaunas literārās un dzejoļu formas, kas atspoguļoja karavīru un ceļotāju pieredzi un emocionālo stāvokli. Episkie dzejoļi un vēstures kronikas par krustakariem bija populāri Eiropā, kā arī bagātināja literāro mantojumu un izpratni par šiem notikumiem.\n\n3. Kultūras apmaiņa: Krustakari veicināja kultūras un ideju apmaiņu starp Eiropu un Tuvo Austrumu reģioniem, kas radīja jaunas mākslas un zinātnes formas. Kontakts ar musulmaņu, bizantiešu un ebreju kultūru veicināja jaunu ideju un prakšu apmaiņu, kas veidoja daudzveidīgu un bagātu kultūras ainu.\n\nKrustakaru ietekme uz kultūru un mākslu bija plaša un daudzveidīga, veidojot pamatu turpmākai kultūras attīstībai un apmaiņai starp reģioniem un kopienu.",
            img: IMG1,
        },
        12: {
            title: "IV. Kultūras sekas",
            sub: "C. Mitoloģija un leģendas par krustakariem",
            content: "Krustakari ir izraisījuši plašu mitoloģiju un leģendu attīstību, kas veidoja daudzveidīgu un bagātu tēlu pasaules krustakaru laikā. Šie stāsti un uzskati atspoguļo dažādas kultūras un reliģiskās tradīcijas, kā arī veidoja mitoloģisko un simbolisko tēlu krustakaru kustībai un tās ietekmei uz sabiedrību.\n\n1. Romantizētie stāsti: Daudzi romantizēti stāsti un leģendas par krustakariem atspoguļoja bruņinieku drosmi un piedzīvojumus Svētajās zemēs. Šie stāsti bieži tika izmantoti kā propagandas līdzeklis, lai veicinātu krustakaru ideju un motivētu jaunus brīvprātīgos piedalīties karā.\n\n2. Reliģiskās leģendas: Dažas reliģiskās kopienas un kultūras radīja savas leģendas un mitus par svēto karu un krustakariem. Šie stāsti bieži uzsverēja krusta kara svētumu un reliģisko nozīmi, kā arī veicināja garīgo entuziasmu un devotēm pret krustakariem.\n\n3. Folkloras un mākslas tēli: Krustakari bieži parādās kā tēli folkloras pasakās, dziesmās un mākslā, atspoguļojot sabiedrības izpratni un tēlus par šiem notikumiem. Šie tēli bieži ir romantizēti un ideālizēti, atspoguļojot cilvēku vēlmes un cerības saistībā ar krusta karu un tās sekām.\n\nMitoloģija un leģendas par krustakariem ir bagātas un daudzveidīgas, atspoguļojot cilvēku izpratni un tēlus par šiem vēsturiskajiem notikumiem.",
            img: IMG1,
        }
    }

    const { id } = useParams();
    const paper = papers[id];
    const [fontSize, setFontSize] = useState(16);
    const [step] = useState(2);

    const decreaseFontSize = () => {
        setFontSize(prevFontSize => prevFontSize - step);
    };

    const increaseFontSize = () => {
        setFontSize(prevFontSize => prevFontSize + step);
    };

    return (
        <div className="cont paper-cont">
        <div className="nav-paper"><Navbar/></div>
        <div className="box paper">
            <div className="paper-title">
                <div className="paper-title-sub">
                    <h1>{paper.title}</h1>
                    <h3>{paper.sub}</h3>
                </div>
                <div className="fontSize">
                    <button className="fontSize-elem" onClick={decreaseFontSize}>-</button>
                    <button className="fontSize-elem" onClick={increaseFontSize}>+</button>
                </div>
            </div>
            <p style={{ fontSize: `${fontSize}px` }}>{paper.content}</p>
            <img src={paper.img} alt="img"/>
        </div>
        </div>
    );
}
